"""add_task_fields

Revision ID: 291a2d6e0d79
Revises: 09fb90452b3a
Create Date: 2025-05-15 03:12:39.941292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '291a2d6e0d79'
down_revision: Union[str, None] = '09fb90452b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'budget_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('project', 'hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('project', 'is_active')
    op.drop_column('project', 'client_id')
    op.drop_constraint('project_team_members_project_id_fkey', 'project_team_members', type_='foreignkey')
    op.drop_constraint('project_team_members_user_id_fkey', 'project_team_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_team_members', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_team_members', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('task', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_task_project', 'task', type_='foreignkey')
    op.drop_constraint('fk_task_assignee', 'task', type_='foreignkey')
    op.drop_constraint('fk_task_creator', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['assigned_to_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'user', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.alter_column('timeentry', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('timeentry', 'hourly_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=False)
    op.drop_column('timeentry', 'duration')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'quota_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('quota_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_user_username', 'user', ['username'], unique=False)
    op.add_column('timeentry', sa.Column('duration', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.alter_column('timeentry', 'hourly_rate',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('timeentry', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('fk_task_creator', 'task', 'user', ['created_by_id'], ['id'])
    op.create_foreign_key('fk_task_assignee', 'task', 'user', ['assigned_to_id'], ['id'])
    op.create_foreign_key('fk_task_project', 'task', 'project', ['project_id'], ['id'])
    op.alter_column('task', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'project_team_members', type_='foreignkey')
    op.drop_constraint(None, 'project_team_members', type_='foreignkey')
    op.create_foreign_key('project_team_members_user_id_fkey', 'project_team_members', 'user', ['user_id'], ['id'])
    op.create_foreign_key('project_team_members_project_id_fkey', 'project_team_members', 'project', ['project_id'], ['id'])
    op.add_column('project', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('project', 'hourly_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('project', 'budget_hours',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
