"""update_relationships

Revision ID: a31a16b1806c
Revises: 291a2d6e0d79
Create Date: 2025-05-15 03:32:58.005586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31a16b1806c'
down_revision: Union[str, None] = '291a2d6e0d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_project_owner', 'project', type_='foreignkey')
    op.drop_constraint('fk_project_manager', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'user', ['owner_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'project', 'user', ['manager_id'], ['id'], ondelete='SET NULL')
    op.add_column('project_team_members', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('project_team_members', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_team_members', 'updated_at')
    op.drop_column('project_team_members', 'created_at')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key('fk_project_manager', 'project', 'user', ['manager_id'], ['id'])
    op.create_foreign_key('fk_project_owner', 'project', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
